"""Application configuration constants."""

VALID_STATES = ["BACKLOG", "IN PROGRESS", "WAITING", "TESTING", "DONE", "CANCELLED"]
STATE_ALIASES = {
    "IN TESTING": "TESTING",
}
FINISHED_STATES = ["DONE", "CANCELLED"]
DEFAULT_STATE = "BACKLOG"
APP_VERSION = "1.1"
BANNER_INNER_WIDTH = 46
