"""Web API route definitions."""

from .handlers.tasks import (
    api_add_note,
    api_add_subtask,
    api_add_subtask_note,
    api_change_state,
    api_create_task,
    api_delete_note,
    api_delete_subtask,
    api_delete_subtask_note,
    api_delete_task,
    api_edit_note,
    api_edit_subtask,
    api_edit_subtask_note,
    api_edit_task,
)
from .handlers.views import (
    api_apply_template,
    api_get_agenda,
    api_get_blockers,
    api_get_burndown,
    api_get_calendar,
    api_get_gantt,
    api_get_kanban,
    api_get_stats,
    api_get_tag_tasks,
    api_get_tags,
    api_get_tasks,
    api_get_templates,
    api_get_time_tracking,
    api_get_weekly_report,
    api_parse_date,
    api_save_template,
    api_search_tasks,
)
from .handlers.notes import (
    api_create_note,
    api_delete_note_route,
    api_get_note,
    api_get_note_folders,
    api_get_notes,
    api_link_task_note,
    api_move_note_route,
    api_unlink_task_note,
)
from .handlers.system import (
    api_add_blocker,
    api_delete_blocker,
    api_get_config,
    api_get_journals,
    api_get_log,
    api_get_status,
    api_get_sync_status,
    api_log_time,
    api_post_sync_settings,
    api_post_sync_pull,
    api_post_sync_push,
    api_save_config,
    api_switch_journal,
)
from .handlers.jira import (
    api_get_jira,
    api_get_jira_transitions,
    api_post_jira_mark,
    api_post_jira_mark_all,
    api_post_jira_transition,
)


API_ROUTES = {
    # Read endpoints
    ("GET", "/api/tasks"): api_get_tasks,
    ("GET", "/api/agenda"): api_get_agenda,
    ("GET", "/api/calendar"): api_get_calendar,
    ("GET", "/api/kanban"): api_get_kanban,
    ("GET", "/api/gantt"): api_get_gantt,
    ("GET", "/api/stats"): api_get_stats,
    ("GET", "/api/weekly"): api_get_weekly_report,
    ("GET", "/api/burndown"): api_get_burndown,
    ("GET", "/api/tags"): api_get_tags,
    ("GET", "/api/tags/tasks"): api_get_tag_tasks,
    ("GET", "/api/blockers"): api_get_blockers,
    ("GET", "/api/time"): api_get_time_tracking,
    ("GET", "/api/jira"): api_get_jira,
    ("GET", "/api/jira/transitions"): api_get_jira_transitions,
    ("GET", "/api/search"): api_search_tasks,
    ("GET", "/api/parse-date"): api_parse_date,
    ("GET", "/api/templates"): api_get_templates,
    ("POST", "/api/templates/save"): api_save_template,
    ("POST", "/api/templates/apply"): api_apply_template,
    ("GET", "/api/config"): api_get_config,
    ("GET", "/api/log"): api_get_log,
    ("GET", "/api/status"): api_get_status,
    ("GET", "/api/journals"): api_get_journals,
    ("GET", "/api/sync/status"): api_get_sync_status,
    ("GET", "/api/notes"): api_get_notes,
    ("GET", "/api/notes/folders"): api_get_note_folders,
    ("GET", "/api/notes/read"): api_get_note,
    # Write endpoints
    ("POST", "/api/tasks"): api_create_task,
    ("POST", "/api/tasks/state"): api_change_state,
    ("POST", "/api/tasks/edit"): api_edit_task,
    ("POST", "/api/tasks/delete"): api_delete_task,
    ("POST", "/api/tasks/notes"): api_add_note,
    ("POST", "/api/tasks/notes/delete"): api_delete_note,
    ("POST", "/api/tasks/notes/edit"): api_edit_note,
    ("POST", "/api/tasks/subtasks"): api_add_subtask,
    ("POST", "/api/subtasks/edit"): api_edit_subtask,
    ("POST", "/api/subtasks/delete"): api_delete_subtask,
    ("POST", "/api/subtasks/notes"): api_add_subtask_note,
    ("POST", "/api/subtasks/notes/delete"): api_delete_subtask_note,
    ("POST", "/api/subtasks/notes/edit"): api_edit_subtask_note,
    ("POST", "/api/jira/transition"): api_post_jira_transition,
    ("POST", "/api/jira/mark-all"): api_post_jira_mark_all,
    ("POST", "/api/jira/mark"): api_post_jira_mark,
    ("POST", "/api/config"): api_save_config,
    ("POST", "/api/journals/switch"): api_switch_journal,
    ("POST", "/api/tasks/time"): api_log_time,
    ("POST", "/api/blockers/add"): api_add_blocker,
    ("POST", "/api/blockers/delete"): api_delete_blocker,
    ("POST", "/api/sync/pull"): api_post_sync_pull,
    ("POST", "/api/sync/push"): api_post_sync_push,
    ("POST", "/api/sync/settings"): api_post_sync_settings,
    # Notes
    ("POST", "/api/notes"): api_create_note,
    ("POST", "/api/notes/delete"): api_delete_note_route,
    ("POST", "/api/notes/move"): api_move_note_route,
    ("POST", "/api/tasks/notes/link"): api_link_task_note,
    ("POST", "/api/tasks/notes/unlink"): api_unlink_task_note,
}
